// Auto-generated by scripts/bundle-burnpal-venues.mjs
export type BurnpalVenueType = 'food' | 'takeout' | 'gym' | 'recovery' | 'activity'

export interface BurnpalVenueRecord {
  id: string
  type: BurnpalVenueType
  name: string
  area: string
  address: string
  cuisine: string
  rating: number | null
  avgPrice: number | null
  dietScore: number | null
  lat?: number
  lon?: number
  tags?: string[]
  aliases?: string[]
}

export const BURNPAL_VENUES: BurnpalVenueRecord[] = [
  {
    "id": "r001",
    "type": "food",
    "name": "沙野轻食",
    "area": "北京·海淀区",
    "address": "北京市海淀区学院路辅路与清华东路交叉口南140米",
    "cuisine": "轻食",
    "rating": 4.2,
    "avgPrice": 28,
    "dietScore": 5
  },
  {
    "id": "r002",
    "type": "food",
    "name": "眉州东坡（中关村领展点)",
    "area": "北京市·海淀区",
    "address": "海淀区海淀街道丹棱街甲1号6层601",
    "cuisine": "川菜",
    "rating": 4.6,
    "avgPrice": 69,
    "dietScore": 2
  },
  {
    "id": "r003",
    "type": "food",
    "name": "海底捞火锅（万柳店）",
    "area": "北京市·海淀区",
    "address": "海淀区巴沟路2号华联万柳购物中心五层",
    "cuisine": "火锅",
    "rating": 4.6,
    "avgPrice": 110,
    "dietScore": 2
  },
  {
    "id": "r004",
    "type": "food",
    "name": "九本居酒屋（中关村店）",
    "area": "北京市·海淀区",
    "address": "海淀区中关村南三街6号中科资源大厦1层",
    "cuisine": "日料",
    "rating": 4.8,
    "avgPrice": 114,
    "dietScore": 4
  },
  {
    "id": "r005",
    "type": "food",
    "name": "翅客烧烤（北大南门店）",
    "area": "北京市·海淀区",
    "address": "海淀区海淀路19-1中成大厦西小厅",
    "cuisine": "烧烤",
    "rating": 4,
    "avgPrice": 60,
    "dietScore": 1
  },
  {
    "id": "r006",
    "type": "food",
    "name": "星巴克（北京畅春园店）",
    "area": "北京市·海淀区",
    "address": "海淀区颐和园路8号",
    "cuisine": "西餐",
    "rating": 4.2,
    "avgPrice": 38,
    "dietScore": 3
  },
  {
    "id": "r007",
    "type": "food",
    "name": "福楼毕斯罗",
    "area": "北京·国贸",
    "address": "朝阳区东三环中路国贸商城3朝北区B座7层",
    "cuisine": "法餐",
    "rating": 4.3,
    "avgPrice": 310,
    "dietScore": 3
  },
  {
    "id": "r008",
    "type": "food",
    "name": "太二酸菜鱼",
    "area": "北京·国贸",
    "address": "朝阳区财富购物中心2楼",
    "cuisine": "川菜",
    "rating": 4.3,
    "avgPrice": 87,
    "dietScore": 2
  },
  {
    "id": "r009",
    "type": "food",
    "name": "Wagas沃歌斯（北京招商局店）",
    "area": "北京·国贸",
    "address": "朝阳区建国路118号招商大厦1层101室",
    "cuisine": "轻食",
    "rating": 4.4,
    "avgPrice": 80,
    "dietScore": 5
  },
  {
    "id": "r010",
    "type": "food",
    "name": "左庭右院鲜牛肉火锅",
    "area": "北京·国贸",
    "address": "朝阳区悠唐购物中心5层",
    "cuisine": "川菜",
    "rating": 4.8,
    "avgPrice": 135,
    "dietScore": 3
  },
  {
    "id": "r011",
    "type": "food",
    "name": "奈雪的茶（乐成中心PRO店）",
    "area": "北京·国贸",
    "address": "朝阳区东三环中路乐城中心A座一层",
    "cuisine": "茶饮甜品",
    "rating": 4.3,
    "avgPrice": 24,
    "dietScore": 3
  },
  {
    "id": "r012",
    "type": "food",
    "name": "吉野家（财富中心餐厅）",
    "area": "北京·国贸",
    "address": "朝阳区东三环中路7号财富购物中心负一层",
    "cuisine": "日料",
    "rating": 5,
    "avgPrice": 25,
    "dietScore": 3
  },
  {
    "id": "r013",
    "type": "food",
    "name": "油梨树avocadotree(陆家嘴中心店)",
    "area": "上海·浦东新区",
    "address": "上海市浦东新区浦东南路899号陆家嘴中心L+MALL B1层",
    "cuisine": "轻食",
    "rating": 4.7,
    "avgPrice": 45,
    "dietScore": 5
  },
  {
    "id": "r014",
    "type": "food",
    "name": "鮨谷·日料铁板烧(陆家嘴中心店)",
    "area": "上海·浦东新区",
    "address": "上海市浦东新区浦东南路899号陆家嘴中心6楼610号",
    "cuisine": "日料",
    "rating": 4.6,
    "avgPrice": 120,
    "dietScore": 4
  },
  {
    "id": "r015",
    "type": "food",
    "name": "我家餐厅(华山路店)",
    "area": "上海·静安区",
    "address": "上海市静安区华山路229弄7号",
    "cuisine": "本帮菜",
    "rating": 4.5,
    "avgPrice": 90,
    "dietScore": 3
  },
  {
    "id": "r016",
    "type": "food",
    "name": "麦当劳(陆家嘴明珠环店)",
    "area": "上海·浦东新区",
    "address": "上海市浦东新区世纪大道55号东方浮庭2F-1室",
    "cuisine": "快餐",
    "rating": 4.7,
    "avgPrice": 30,
    "dietScore": 2
  },
  {
    "id": "t001",
    "type": "takeout",
    "name": "超级碗FOODBOWL",
    "area": "朝阳区",
    "address": "朝阳区",
    "cuisine": "",
    "rating": 4.2,
    "avgPrice": 38,
    "dietScore": null
  },
  {
    "id": "t002",
    "type": "takeout",
    "name": "蜀大侠火锅",
    "area": "朝阳区",
    "address": "朝阳区",
    "cuisine": "",
    "rating": 5,
    "avgPrice": 57,
    "dietScore": null
  },
  {
    "id": "t003",
    "type": "takeout",
    "name": "川味小厨",
    "area": "朝阳区",
    "address": "朝阳区",
    "cuisine": "",
    "rating": 4.3,
    "avgPrice": 28,
    "dietScore": null
  },
  {
    "id": "t004",
    "type": "takeout",
    "name": "西堤牛排",
    "area": "朝阳区",
    "address": "朝阳区",
    "cuisine": "",
    "rating": 4.6,
    "avgPrice": 110,
    "dietScore": null
  },
  {
    "id": "t005",
    "type": "takeout",
    "name": "老兵烧烤",
    "area": "海淀区",
    "address": "海淀区",
    "cuisine": "",
    "rating": 4.7,
    "avgPrice": 86,
    "dietScore": null
  },
  {
    "id": "t006",
    "type": "takeout",
    "name": "嘉和一品",
    "area": "海淀区",
    "address": "海淀区",
    "cuisine": "",
    "rating": 4.8,
    "avgPrice": 40,
    "dietScore": null
  },
  {
    "id": "t007",
    "type": "takeout",
    "name": "越小官",
    "area": "海淀区",
    "address": "海淀区",
    "cuisine": "",
    "rating": 4.3,
    "avgPrice": 50,
    "dietScore": null
  },
  {
    "id": "t008",
    "type": "takeout",
    "name": "魏家凉皮",
    "area": "海淀区",
    "address": "海淀区",
    "cuisine": "",
    "rating": 4.5,
    "avgPrice": 33,
    "dietScore": null
  },
  {
    "id": "t009",
    "type": "takeout",
    "name": "油梨树avocadotree(陆家嘴中心店)",
    "area": "浦东新区",
    "address": "浦东新区",
    "cuisine": "",
    "rating": 4.7,
    "avgPrice": 45,
    "dietScore": null
  },
  {
    "id": "t010",
    "type": "takeout",
    "name": "刺臂健身餐&轻食谷物饭(陆家嘴店)",
    "area": "浦东新区",
    "address": "浦东新区",
    "cuisine": "",
    "rating": 4.5,
    "avgPrice": 35,
    "dietScore": null
  },
  {
    "id": "t011",
    "type": "takeout",
    "name": "麦当劳(陆家嘴明珠环店)",
    "area": "浦东新区",
    "address": "浦东新区",
    "cuisine": "",
    "rating": 4.7,
    "avgPrice": 30,
    "dietScore": null
  },
  {
    "id": "t012",
    "type": "takeout",
    "name": "粤珍小厨(太平金融大厦店)",
    "area": "浦东新区",
    "address": "浦东新区",
    "cuisine": "",
    "rating": 4.4,
    "avgPrice": 25,
    "dietScore": null
  },
  {
    "id": "t013",
    "type": "takeout",
    "name": "沙野轻食(中关村店)",
    "area": "海淀区",
    "address": "海淀区",
    "cuisine": "",
    "rating": 4.2,
    "avgPrice": 28,
    "dietScore": null
  },
  {
    "id": "t014",
    "type": "takeout",
    "name": "共禾之约(国贸店)",
    "area": "朝阳区",
    "address": "朝阳区",
    "cuisine": "",
    "rating": 4.4,
    "avgPrice": 35,
    "dietScore": null
  },
  {
    "id": "gym_001",
    "type": "gym",
    "name": "乐刻健身(丽泽16号店)",
    "area": "丰台区",
    "address": "北京市丰台区太平桥丽泽16号购物中心2层",
    "cuisine": "",
    "rating": 4.5,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.8761,
    "lon": 116.3132,
    "tags": [
      "有氧区",
      "固定器械"
    ]
  },
  {
    "id": "gym_002",
    "type": "gym",
    "name": "奇迹健身(三元桥店)",
    "area": "朝阳区",
    "address": "北京市朝阳区东三环北路甲2号京信大厦西南配楼2层",
    "cuisine": "",
    "rating": 4.3,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9521,
    "lon": 116.4589,
    "tags": [
      "有氧区",
      "固定器械"
    ]
  },
  {
    "id": "gym_003",
    "type": "gym",
    "name": "U-24健身(中关村店)",
    "area": "海淀区",
    "address": "北京市海淀区中关村大街19号新中关购物中心B1层",
    "cuisine": "",
    "rating": 4.6,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9825,
    "lon": 116.3168,
    "tags": [
      "智能有氧设备",
      "力量训练区"
    ]
  },
  {
    "id": "gym_004",
    "type": "gym",
    "name": "龙星健身(科实大厦店)",
    "area": "海淀区",
    "address": "北京市海淀区信息路甲28号科实大厦A座B1层",
    "cuisine": "",
    "rating": 4.2,
    "avgPrice": null,
    "dietScore": null,
    "lat": 40.0353,
    "lon": 116.3115,
    "tags": [
      "有氧区",
      "力量训练区"
    ]
  },
  {
    "id": "gym_005",
    "type": "gym",
    "name": "北京海航大厦万豪酒店健身中心",
    "area": "朝阳区",
    "address": "北京市霄云路甲26号北京海航大厦万豪酒店6层",
    "cuisine": "",
    "rating": 4.8,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9598,
    "lon": 116.4673,
    "tags": [
      "高端有氧器械",
      "综合力量区"
    ]
  },
  {
    "id": "gym_006",
    "type": "gym",
    "name": "乐刻运动健身(世茂52+店)",
    "area": "浦东新区",
    "address": "上海市浦东新区潍坊西路67号世茂滨江商务区F3层3091A",
    "cuisine": "",
    "rating": 4.5,
    "avgPrice": null,
    "dietScore": null,
    "lat": 31.2256,
    "lon": 121.5123,
    "tags": [
      "有氧区",
      "固定器械"
    ]
  },
  {
    "id": "gym_007",
    "type": "gym",
    "name": "超级猩猩健身(浦东中心全能店)",
    "area": "浦东新区",
    "address": "上海市浦东新区世纪大道201号渣打银行大厦二层203单元",
    "cuisine": "",
    "rating": 4.7,
    "avgPrice": null,
    "dietScore": null,
    "lat": 31.2354,
    "lon": 121.5087,
    "tags": [
      "团操教室",
      "有氧器械"
    ]
  },
  {
    "id": "gym_008",
    "type": "gym",
    "name": "上海静安瑞吉酒店健身中心",
    "area": "静安区",
    "address": "上海市静安区北京西路1008号上海静安瑞吉酒店5层",
    "cuisine": "",
    "rating": 4.9,
    "avgPrice": null,
    "dietScore": null,
    "lat": 31.2289,
    "lon": 121.4567,
    "tags": [
      "高端有氧器械",
      "综合力量区"
    ]
  },
  {
    "id": "venue_001",
    "type": "gym",
    "name": "东单体育中心",
    "area": "东城区",
    "address": "北京市东城区崇文门内大街108号",
    "cuisine": "运动场馆",
    "rating": 4.7,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9087,
    "lon": 116.4123
  },
  {
    "id": "venue_002",
    "type": "gym",
    "name": "五棵松HI-PARK篮球公园",
    "area": "海淀区",
    "address": "北京市海淀区复兴路69号",
    "cuisine": "运动场馆",
    "rating": 4.8,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9065,
    "lon": 116.2897
  },
  {
    "id": "venue_003",
    "type": "gym",
    "name": "地坛体育中心",
    "area": "东城区",
    "address": "北京市东城区安定门外大街168号",
    "cuisine": "运动场馆",
    "rating": 4.4,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9567,
    "lon": 116.4078
  },
  {
    "id": "venue_004",
    "type": "gym",
    "name": "通州体育场",
    "area": "通州区",
    "address": "北京市通州区新华街道新华东街77号",
    "cuisine": "运动场馆",
    "rating": 4.6,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9012,
    "lon": 116.6543
  },
  {
    "id": "venue_005",
    "type": "gym",
    "name": "北投奥园1314",
    "area": "朝阳区",
    "address": "北京市朝阳区奥园西路1号院",
    "cuisine": "运动场馆",
    "rating": 4.7,
    "avgPrice": null,
    "dietScore": null,
    "lat": 40.0023,
    "lon": 116.3987
  },
  {
    "id": "venue_006",
    "type": "gym",
    "name": "源深体育中心",
    "area": "浦东新区",
    "address": "上海市浦东新区洋泾街道源深路655号",
    "cuisine": "运动场馆",
    "rating": 4.7,
    "avgPrice": null,
    "dietScore": null,
    "lat": 31.2345,
    "lon": 121.5234
  },
  {
    "id": "venue_007",
    "type": "gym",
    "name": "静安体育中心",
    "area": "静安区",
    "address": "上海市静安区汶水路116号",
    "cuisine": "运动场馆",
    "rating": 4.8,
    "avgPrice": null,
    "dietScore": null,
    "lat": 31.2678,
    "lon": 121.4456
  },
  {
    "id": "recovery_001",
    "type": "recovery",
    "name": "整整运动按摩(东大桥店)",
    "area": "朝阳区",
    "address": "北京市朝阳区SOHO尚都北塔负一层B163",
    "cuisine": "运动按摩中心",
    "rating": 4.6,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9188,
    "lon": 116.4529
  },
  {
    "id": "recovery_002",
    "type": "recovery",
    "name": "乙子运动康复中心(世贸天街店)",
    "area": "朝阳区",
    "address": "北京市朝阳区东大桥路8号SOHO·尚都南塔29楼2903室",
    "cuisine": "专业运动康复中心",
    "rating": 4.4,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9185,
    "lon": 116.4532
  },
  {
    "id": "recovery_003",
    "type": "recovery",
    "name": "轻松猫·疼痛康复·运动复健(望京店)",
    "area": "朝阳区",
    "address": "北京市朝阳区启阳路望京东园四区5号楼昆泰嘉瑞公寓1505室",
    "cuisine": "疼痛康复中心",
    "rating": 4.3,
    "avgPrice": null,
    "dietScore": null,
    "lat": 40.0012,
    "lon": 116.4876
  },
  {
    "id": "recovery_004",
    "type": "recovery",
    "name": "松松堂·按摩·艾灸·拉伸·康复(国贸店)",
    "area": "朝阳区",
    "address": "北京市朝阳区景恒街建外soho东区9号楼商铺区3层9317号",
    "cuisine": "综合康复按摩店",
    "rating": 4.2,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9078,
    "lon": 116.4654
  },
  {
    "id": "recovery_005",
    "type": "recovery",
    "name": "运动康复中心(中关村店)",
    "area": "海淀区",
    "address": "北京市海淀区中关村街道中关村大厦16层1621室",
    "cuisine": "专业运动康复中心",
    "rating": 4.5,
    "avgPrice": null,
    "dietScore": null,
    "lat": 39.9821,
    "lon": 116.3165
  },
  {
    "id": "recovery_006",
    "type": "recovery",
    "name": "常乐推拿(陆家嘴中心L+店)",
    "area": "浦东新区",
    "address": "上海市浦东新区浦东南路899号陆家嘴中心L+MALL 8F",
    "cuisine": "运动推拿/拉伸中心",
    "rating": 4.5,
    "avgPrice": null,
    "dietScore": null,
    "lat": 31.2345,
    "lon": 121.5123
  },
  {
    "id": "recovery_007",
    "type": "recovery",
    "name": "优复门诊(静安店)",
    "area": "静安区",
    "address": "上海市静安区大沽路432号",
    "cuisine": "专业运动康复中心",
    "rating": 4.7,
    "avgPrice": null,
    "dietScore": null,
    "lat": 31.2234,
    "lon": 121.4567
  },
  {
    "id": "act001",
    "type": "activity",
    "name": "国贸中心户外跑道",
    "area": "朝阳区·国贸",
    "address": "朝阳区建国门外大街国贸中心外环形跑道",
    "cuisine": "跑步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "社交"
    ],
    "aliases": [
      "国贸CBD夜跑团"
    ]
  },
  {
    "id": "act002",
    "type": "activity",
    "name": "中关村文体活动中心",
    "area": "海淀区·中关村",
    "address": "海淀区知春路1号文体活动中心3楼",
    "cuisine": "羽毛球",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "有教练",
      "社交"
    ],
    "aliases": [
      "中关村周末羽毛球局"
    ]
  },
  {
    "id": "act003",
    "type": "activity",
    "name": "国贸附近城市公园",
    "area": "朝阳区·国贸",
    "address": "朝阳区建国路城市公园草坪",
    "cuisine": "飞盘",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "社交"
    ],
    "aliases": [
      "国贸新手飞盘体验局"
    ]
  },
  {
    "id": "act004",
    "type": "activity",
    "name": "学院路绿道集合点",
    "area": "海淀区·中关村",
    "address": "海淀区学院路与北四环交叉口绿道入口",
    "cuisine": "骑行",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "不卷"
    ],
    "aliases": [
      "中关村周边休闲骑行"
    ]
  },
  {
    "id": "act005",
    "type": "activity",
    "name": "集合点：中关村地铁站",
    "area": "海淀区·中关村",
    "address": "海淀区中关村地铁站A口",
    "cuisine": "徒步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "社交",
      "风景好"
    ],
    "aliases": [
      "近郊轻徒步一日游"
    ]
  },
  {
    "id": "act006",
    "type": "activity",
    "name": "国贸中心户外跑道",
    "area": "朝阳区·国贸",
    "address": "朝阳区建国门外大街国贸中心外环形跑道",
    "cuisine": "跑步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "不卷",
      "早鸟"
    ],
    "aliases": [
      "早鸟晨跑5km"
    ]
  },
  {
    "id": "act007",
    "type": "activity",
    "name": "中关村文体活动中心",
    "area": "海淀区·中关村",
    "address": "海淀区知春路1号文体活动中心3楼",
    "cuisine": "羽毛球",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "社交",
      "减压"
    ],
    "aliases": [
      "晚间减压羽毛球局"
    ]
  },
  {
    "id": "act008",
    "type": "activity",
    "name": "国贸附近城市公园",
    "area": "朝阳区·国贸",
    "address": "朝阳区建国路城市公园草坪",
    "cuisine": "飞盘",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "进阶友好",
      "竞技"
    ],
    "aliases": [
      "进阶飞盘攻防赛"
    ]
  },
  {
    "id": "act009",
    "type": "activity",
    "name": "国贸地铁站集合点",
    "area": "朝阳区·国贸",
    "address": "朝阳区国贸地铁站C口",
    "cuisine": "骑行",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "夜景",
      "社交"
    ],
    "aliases": [
      "城市夜骑休闲局"
    ]
  },
  {
    "id": "act010",
    "type": "activity",
    "name": "香山公园东门集合点",
    "area": "海淀区·中关村",
    "address": "海淀区香山公园东门",
    "cuisine": "徒步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "风景好",
      "新手友好"
    ],
    "aliases": [
      "香山轻徒步赏景"
    ]
  },
  {
    "id": "act011",
    "type": "activity",
    "name": "中关村软件园跑道",
    "area": "海淀区·中关村",
    "address": "海淀区中关村软件园户外跑道",
    "cuisine": "跑步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "进阶友好",
      "有配速"
    ],
    "aliases": [
      "配速跑进阶局"
    ]
  },
  {
    "id": "act012",
    "type": "activity",
    "name": "国贸附近社区球馆",
    "area": "朝阳区·国贸",
    "address": "朝阳区光华路社区文体中心2楼",
    "cuisine": "羽毛球",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "有教练"
    ],
    "aliases": [
      "新手友好羽球教学局"
    ]
  },
  {
    "id": "act013",
    "type": "activity",
    "name": "中关村软件园草坪",
    "area": "海淀区·中关村",
    "address": "海淀区中关村软件园中心草坪",
    "cuisine": "飞盘",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "趣味",
      "社交"
    ],
    "aliases": [
      "周末飞盘趣味赛"
    ]
  },
  {
    "id": "act014",
    "type": "activity",
    "name": "国贸地铁站集合点",
    "area": "朝阳区·国贸",
    "address": "朝阳区国贸地铁站A口",
    "cuisine": "骑行",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "地标打卡",
      "城市骑行"
    ],
    "aliases": [
      "长安街经典骑行路线"
    ]
  },
  {
    "id": "act015",
    "type": "activity",
    "name": "阳台山景区集合点",
    "area": "海淀区·中关村",
    "address": "海淀区阳台山景区入口",
    "cuisine": "徒步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "风景好",
      "有领队"
    ],
    "aliases": [
      "阳台山轻徒步"
    ]
  },
  {
    "id": "act016",
    "type": "activity",
    "name": "中关村软件园跑道",
    "area": "海淀区·中关村",
    "address": "海淀区中关村软件园户外跑道",
    "cuisine": "跑步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "进阶友好",
      "耐力挑战"
    ],
    "aliases": [
      "10km耐力跑挑战"
    ]
  },
  {
    "id": "act017",
    "type": "activity",
    "name": "国贸附近商务球馆",
    "area": "朝阳区·国贸",
    "address": "朝阳区建国门外大街商务楼B1层球馆",
    "cuisine": "羽毛球",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "商务友好",
      "午休运动"
    ],
    "aliases": [
      "国贸商务羽球局"
    ]
  },
  {
    "id": "act018",
    "type": "activity",
    "name": "中关村软件园草坪",
    "area": "海淀区·中关村",
    "address": "海淀区中关村软件园中心草坪",
    "cuisine": "飞盘",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "教学为主"
    ],
    "aliases": [
      "新手飞盘零基础教学"
    ]
  },
  {
    "id": "act019",
    "type": "activity",
    "name": "奥林匹克森林公园南门",
    "area": "朝阳区·国贸",
    "address": "朝阳区奥林匹克森林公园南门",
    "cuisine": "骑行",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "公园骑行",
      "风景好"
    ],
    "aliases": [
      "奥森休闲骑行"
    ]
  },
  {
    "id": "act020",
    "type": "activity",
    "name": "百望山森林公园入口",
    "area": "海淀区·中关村",
    "address": "海淀区百望山森林公园入口",
    "cuisine": "徒步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "城市周边"
    ],
    "aliases": [
      "百望山轻徒步"
    ]
  },
  {
    "id": "act021",
    "type": "activity",
    "name": "国贸附近城市公园跑道",
    "area": "朝阳区·国贸",
    "address": "朝阳区建国路城市公园环形跑道",
    "cuisine": "跑步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "短距离"
    ],
    "aliases": [
      "公园夜跑3km"
    ]
  },
  {
    "id": "act022",
    "type": "activity",
    "name": "国贸附近社区球馆",
    "area": "朝阳区·国贸",
    "address": "朝阳区光华路社区文体中心2楼",
    "cuisine": "羽毛球",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "进阶友好",
      "对抗为主"
    ],
    "aliases": [
      "进阶羽球对抗局"
    ]
  },
  {
    "id": "act023",
    "type": "activity",
    "name": "国贸附近城市公园",
    "area": "朝阳区·国贸",
    "address": "朝阳区建国路城市公园草坪",
    "cuisine": "飞盘",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "团建友好",
      "社交"
    ],
    "aliases": [
      "企业飞盘团建局"
    ]
  },
  {
    "id": "act024",
    "type": "activity",
    "name": "温榆河绿道集合点",
    "area": "海淀区·中关村",
    "address": "海淀区温榆河绿道入口",
    "cuisine": "骑行",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "风景好",
      "绿道骑行"
    ],
    "aliases": [
      "温榆河绿道骑行"
    ]
  },
  {
    "id": "act025",
    "type": "activity",
    "name": "凤凰岭景区集合点",
    "area": "海淀区·中关村",
    "address": "海淀区凤凰岭景区入口",
    "cuisine": "徒步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "风景好",
      "有领队"
    ],
    "aliases": [
      "凤凰岭轻徒步"
    ]
  },
  {
    "id": "act026",
    "type": "activity",
    "name": "徐汇滨江跑道",
    "area": "浦东新区·陆家嘴",
    "address": "上海市徐汇区龙腾大道",
    "cuisine": "跑步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "江景"
    ],
    "aliases": [
      "陆家嘴滨江夜跑团"
    ]
  },
  {
    "id": "act027",
    "type": "activity",
    "name": "世纪公园",
    "area": "浦东新区·陆家嘴",
    "address": "上海市浦东新区锦绣路1001号",
    "cuisine": "飞盘",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "新手友好",
      "社交"
    ],
    "aliases": [
      "世纪公园新手飞盘局"
    ]
  },
  {
    "id": "act028",
    "type": "activity",
    "name": "浦东世博骑行道",
    "area": "浦东新区",
    "address": "上海市浦东新区世博大道",
    "cuisine": "骑行",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "江景",
      "新手友好"
    ],
    "aliases": [
      "浦东世博滨江骑行"
    ]
  },
  {
    "id": "act029",
    "type": "activity",
    "name": "静安体育中心",
    "area": "静安区",
    "address": "上海市静安区汶水路116号",
    "cuisine": "羽毛球",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "社交",
      "下班友好"
    ],
    "aliases": [
      "静安体育中心羽球局"
    ]
  },
  {
    "id": "act030",
    "type": "activity",
    "name": "世纪公园",
    "area": "浦东新区·陆家嘴",
    "address": "上海市浦东新区锦绣路1001号",
    "cuisine": "徒步",
    "rating": null,
    "avgPrice": null,
    "dietScore": null,
    "tags": [
      "风景好",
      "新手友好"
    ],
    "aliases": [
      "世纪公园休闲徒步"
    ]
  }
]
