// Auto-generated by scripts/bundle-qinglu-demo-profiles.mjs
export interface DemoProfileTodayMeal {
  meal: string
  items: string
  estimated_kcal: number
}

export interface DemoProfileToday {
  training_plan: string
  meals_logged: DemoProfileTodayMeal[]
  total_intake_kcal: number
  remaining_kcal: number
}

export interface DemoProfileLocation {
  city: string
  work: string
  home: string
  current: string
}

export interface DemoProfileRecord {
  id: string
  name: string
  gender: 'male' | 'female'
  age: number
  height_cm: number
  weight_kg: number
  target_weight_kg: number
  bmr_kcal: number
  tdee_kcal: number
  daily_target_kcal: number
  activity_level: string
  training_type: string
  training_frequency: string
  dietary_restrictions: string[]
  taste_preferences: string[]
  budget_per_meal_yuan: number
  budget_dining_per_person_yuan: number
  location: DemoProfileLocation
  today: DemoProfileToday
  sport_interests: string[]
  preferred_scale: string
  preferred_time: string
}

export const DEMO_PROFILES: DemoProfileRecord[] = [
  {
    "id": "user_a",
    "name": "小明",
    "gender": "male",
    "age": 30,
    "height_cm": 180,
    "weight_kg": 82,
    "target_weight_kg": 75,
    "bmr_kcal": 1830,
    "tdee_kcal": 2720,
    "daily_target_kcal": 2200,
    "activity_level": "heavy",
    "training_type": "strength",
    "training_frequency": "5x/week",
    "dietary_restrictions": [
      "不吃甜食"
    ],
    "taste_preferences": [
      "重咸",
      "高蛋白肉食"
    ],
    "budget_per_meal_yuan": 48,
    "budget_dining_per_person_yuan": 140,
    "location": {
      "city": "北京",
      "work": "朝阳区·国贸",
      "home": "朝阳区·望京",
      "current": "朝阳区·国贸"
    },
    "today": {
      "training_plan": "胸+肩",
      "meals_logged": [
        {
          "meal": "早餐",
          "items": "全麦吐司3片+煎蛋2个+无糖酸奶",
          "estimated_kcal": 420
        }
      ],
      "total_intake_kcal": 420,
      "remaining_kcal": 1780
    },
    "sport_interests": [
      "篮球",
      "引体向上",
      "跑步"
    ],
    "preferred_scale": "large",
    "preferred_time": "晚上"
  },
  {
    "id": "user_b",
    "name": "小红",
    "gender": "female",
    "age": 25,
    "height_cm": 163,
    "weight_kg": 55,
    "target_weight_kg": 50,
    "bmr_kcal": 1320,
    "tdee_kcal": 1760,
    "daily_target_kcal": 1380,
    "activity_level": "light",
    "training_type": "light_exercise",
    "training_frequency": "3x/week",
    "dietary_restrictions": [
      "不吃生冷",
      "少食主食"
    ],
    "taste_preferences": [
      "鲜香",
      "果蔬搭配"
    ],
    "budget_per_meal_yuan": 42,
    "budget_dining_per_person_yuan": 95,
    "location": {
      "city": "北京",
      "work": "海淀区·中关村",
      "home": "海淀区·中关村",
      "current": "海淀区·中关村"
    },
    "today": {
      "training_plan": "快走+体态拉伸",
      "meals_logged": [
        {
          "meal": "早餐",
          "items": "杂粮粥+水煮蛋1个+小番茄",
          "estimated_kcal": 200
        },
        {
          "meal": "午餐",
          "items": "清炒时蔬+去皮鸡腿肉",
          "estimated_kcal": 360
        }
      ],
      "total_intake_kcal": 560,
      "remaining_kcal": 820
    },
    "sport_interests": [
      "羽毛球",
      "慢跑",
      "徒步"
    ],
    "preferred_scale": "small",
    "preferred_time": "白天"
  },
  {
    "id": "user_c",
    "name": "王总",
    "gender": "male",
    "age": 29,
    "height_cm": 175,
    "weight_kg": 76,
    "target_weight_kg": 71,
    "bmr_kcal": 1720,
    "tdee_kcal": 2280,
    "daily_target_kcal": 1830,
    "activity_level": "moderate",
    "training_type": "mixed",
    "training_frequency": "2x/week",
    "dietary_restrictions": [
      "不吃油炸",
      "控制高糖"
    ],
    "taste_preferences": [
      "家常口味",
      "荤素均衡"
    ],
    "budget_per_meal_yuan": 52,
    "budget_dining_per_person_yuan": 160,
    "location": {
      "city": "上海",
      "work": "浦东新区·陆家嘴",
      "home": "北京朝阳区·望京",
      "current": "浦东新区·陆家嘴"
    },
    "today": {
      "training_plan": "徒手居家训练",
      "meals_logged": [
        {
          "meal": "早餐",
          "items": "牛奶+水煮蛋+玉米",
          "estimated_kcal": 320
        },
        {
          "meal": "午餐",
          "items": "轻食便当+清蒸鱼肉",
          "estimated_kcal": 480
        }
      ],
      "total_intake_kcal": 800,
      "remaining_kcal": 1030
    },
    "sport_interests": [
      "慢跑",
      "徒步"
    ],
    "preferred_scale": "medium",
    "preferred_time": "傍晚"
  }
]
