// Auto-generated by scripts/bundle-qinglu-takeout.mjs
export interface QingluTakeoutCombo {
  name: string
  kcal_range: string
  protein_g: number | null
  price_yuan: number | null
  warnings: string[]
  tags: string[]
}

export interface QingluTakeoutRecord {
  id: string
  name: string
  area: string
  rating: number | null
  avg_price_yuan: number | null
  delivery_time_min: number | null
  combos: QingluTakeoutCombo[]
}

export const QINGLU_TAKEOUT: QingluTakeoutRecord[] = [
  {
    "id": "t001",
    "name": "超级碗FOODBOWL",
    "area": "朝阳区",
    "rating": 4.2,
    "avg_price_yuan": 38,
    "delivery_time_min": 30,
    "combos": [
      {
        "name": "鸡胸肉超级碗+米饭",
        "kcal_range": "430-480",
        "protein_g": 35,
        "price_yuan": 30,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白"
        ]
      },
      {
        "name": "牛肉超级碗+藜麦",
        "kcal_range": "380-430",
        "protein_g": 32,
        "price_yuan": 38,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白",
          "低碳水"
        ]
      }
    ]
  },
  {
    "id": "t002",
    "name": "蜀大侠火锅",
    "area": "朝阳区",
    "rating": 5,
    "avg_price_yuan": 57,
    "delivery_time_min": 40,
    "combos": [
      {
        "name": "约会不怂双人套餐",
        "kcal_range": "1200-1350",
        "protein_g": 65,
        "price_yuan": 168,
        "warnings": [
          "高油高盐",
          "热量较高"
        ],
        "tags": [
          "推荐",
          "聚餐"
        ]
      },
      {
        "name": "单人解馋套餐",
        "kcal_range": "450-520",
        "protein_g": 22,
        "price_yuan": 68,
        "warnings": [
          "可选择清汤锅底减少热量"
        ],
        "tags": [
          "单人"
        ]
      }
    ]
  },
  {
    "id": "t003",
    "name": "川味小厨",
    "area": "朝阳区",
    "rating": 4.3,
    "avg_price_yuan": 28,
    "delivery_time_min": 25,
    "combos": [
      {
        "name": "鱼香肉丝盖饭",
        "kcal_range": "550-600",
        "protein_g": 22,
        "price_yuan": 26,
        "warnings": [
          "可做少油少盐版"
        ],
        "tags": [
          "工作餐",
          "家常"
        ]
      },
      {
        "name": "清炒时蔬+蒸蛋套餐",
        "kcal_range": "320-370",
        "protein_g": 15,
        "price_yuan": 18,
        "warnings": [],
        "tags": [
          "清淡",
          "低卡"
        ]
      }
    ]
  },
  {
    "id": "t004",
    "name": "西堤牛排",
    "area": "朝阳区",
    "rating": 4.6,
    "avg_price_yuan": 110,
    "delivery_time_min": 30,
    "combos": [
      {
        "name": "黑椒牛排单人餐",
        "kcal_range": "580-630",
        "protein_g": 38,
        "price_yuan": 90,
        "warnings": [
          "可调整熟度与酱料"
        ],
        "tags": [
          "商务简餐",
          "增肌"
        ]
      },
      {
        "name": "香煎三文鱼套餐",
        "kcal_range": "450-510",
        "protein_g": 25,
        "price_yuan": 108,
        "warnings": [],
        "tags": [
          "高蛋白",
          "健康"
        ]
      }
    ]
  },
  {
    "id": "t005",
    "name": "老兵烧烤",
    "area": "海淀区",
    "rating": 4.7,
    "avg_price_yuan": 86,
    "delivery_time_min": 35,
    "combos": [
      {
        "name": "双人烧烤套餐",
        "kcal_range": "900-1050",
        "protein_g": 45,
        "price_yuan": 125,
        "warnings": [
          "高油高盐",
          "热量偏高"
        ],
        "tags": [
          "夜宵",
          "聚餐"
        ]
      },
      {
        "name": "单人烤串套餐",
        "kcal_range": "450-520",
        "protein_g": 18,
        "price_yuan": 45,
        "warnings": [
          "高油高盐"
        ],
        "tags": [
          "单人"
        ]
      }
    ]
  },
  {
    "id": "t006",
    "name": "嘉和一品",
    "area": "海淀区",
    "rating": 4.8,
    "avg_price_yuan": 40,
    "delivery_time_min": 25,
    "combos": [
      {
        "name": "早餐自选套餐",
        "kcal_range": "380-430",
        "protein_g": 40,
        "price_yuan": 22,
        "warnings": [],
        "tags": [
          "减脂餐",
          "高蛋白"
        ]
      },
      {
        "name": "午餐营养套餐",
        "kcal_range": "350-400",
        "protein_g": 28,
        "price_yuan": 35,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白"
        ]
      }
    ]
  },
  {
    "id": "t007",
    "name": "越小官",
    "area": "海淀区",
    "rating": 4.3,
    "avg_price_yuan": 50,
    "delivery_time_min": 30,
    "combos": [
      {
        "name": "冬阴功汤",
        "kcal_range": "750-850",
        "protein_g": 30,
        "price_yuan": 138,
        "warnings": [
          "微辣可选",
          "椰浆含量较高"
        ],
        "tags": [
          "东南亚菜",
          "酸辣口"
        ]
      },
      {
        "name": "越南春卷套餐",
        "kcal_range": "250-300",
        "protein_g": 12,
        "price_yuan": 48,
        "warnings": [],
        "tags": [
          "低卡",
          "清淡"
        ]
      }
    ]
  },
  {
    "id": "t008",
    "name": "魏家凉皮",
    "area": "海淀区",
    "rating": 4.5,
    "avg_price_yuan": 33,
    "delivery_time_min": 25,
    "combos": [
      {
        "name": "麻酱凉皮",
        "kcal_range": "600-650",
        "protein_g": 24,
        "price_yuan": 18,
        "warnings": [
          "麻酱热量较高"
        ],
        "tags": [
          "工作餐",
          "简餐"
        ]
      },
      {
        "name": "秘制凉皮+肉夹馍",
        "kcal_range": "750-820",
        "protein_g": 22,
        "price_yuan": 28,
        "warnings": [
          "热量较高"
        ],
        "tags": [
          "工作餐"
        ]
      }
    ]
  },
  {
    "id": "t009",
    "name": "油梨树avocadotree(陆家嘴中心店)",
    "area": "浦东新区",
    "rating": 4.7,
    "avg_price_yuan": 45,
    "delivery_time_min": 30,
    "combos": [
      {
        "name": "鸡腿羽衣甘蓝碗",
        "kcal_range": "350-420",
        "protein_g": 28,
        "price_yuan": 38,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白",
          "热沙拉"
        ]
      },
      {
        "name": "和牛扒碗里道",
        "kcal_range": "420-480",
        "protein_g": 30,
        "price_yuan": 52,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白"
        ]
      }
    ]
  },
  {
    "id": "t010",
    "name": "刺臂健身餐&轻食谷物饭(陆家嘴店)",
    "area": "浦东新区",
    "rating": 4.5,
    "avg_price_yuan": 35,
    "delivery_time_min": 28,
    "combos": [
      {
        "name": "强劲鸡腿肉套餐",
        "kcal_range": "320-380",
        "protein_g": 26,
        "price_yuan": 32,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白",
          "减脂"
        ]
      },
      {
        "name": "柠烤龙利鱼套餐",
        "kcal_range": "280-340",
        "protein_g": 24,
        "price_yuan": 36,
        "warnings": [],
        "tags": [
          "推荐",
          "低卡",
          "高蛋白"
        ]
      }
    ]
  },
  {
    "id": "t011",
    "name": "麦当劳(陆家嘴明珠环店)",
    "area": "浦东新区",
    "rating": 4.7,
    "avg_price_yuan": 30,
    "delivery_time_min": 25,
    "combos": [
      {
        "name": "吉士汉堡套餐",
        "kcal_range": "380-430",
        "protein_g": 18,
        "price_yuan": 28,
        "warnings": [
          "可选择无糖饮料"
        ],
        "tags": [
          "工作餐",
          "简餐"
        ]
      },
      {
        "name": "麦乐鸡套餐",
        "kcal_range": "420-470",
        "protein_g": 12,
        "price_yuan": 25,
        "warnings": [
          "薯条热量较高"
        ],
        "tags": [
          "简餐"
        ]
      }
    ]
  },
  {
    "id": "t012",
    "name": "粤珍小厨(太平金融大厦店)",
    "area": "浦东新区",
    "rating": 4.4,
    "avg_price_yuan": 25,
    "delivery_time_min": 22,
    "combos": [
      {
        "name": "香菇滑鸡饭",
        "kcal_range": "450-510",
        "protein_g": 20,
        "price_yuan": 22,
        "warnings": [],
        "tags": [
          "工作餐",
          "家常"
        ]
      },
      {
        "name": "清蒸排骨饭",
        "kcal_range": "420-480",
        "protein_g": 18,
        "price_yuan": 25,
        "warnings": [],
        "tags": [
          "工作餐"
        ]
      }
    ]
  },
  {
    "id": "t013",
    "name": "沙野轻食(中关村店)",
    "area": "海淀区",
    "rating": 4.2,
    "avg_price_yuan": 28,
    "delivery_time_min": 28,
    "combos": [
      {
        "name": "藤椒鸡腿健身餐",
        "kcal_range": "300-360",
        "protein_g": 25,
        "price_yuan": 26,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白",
          "减脂"
        ]
      },
      {
        "name": "烤鸡胸藜麦沙拉",
        "kcal_range": "200-260",
        "protein_g": 30,
        "price_yuan": 28,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白",
          "低卡"
        ]
      }
    ]
  },
  {
    "id": "t014",
    "name": "共禾之约(国贸店)",
    "area": "朝阳区",
    "rating": 4.4,
    "avg_price_yuan": 35,
    "delivery_time_min": 30,
    "combos": [
      {
        "name": "烤牛肉藜麦碗",
        "kcal_range": "380-440",
        "protein_g": 28,
        "price_yuan": 36,
        "warnings": [],
        "tags": [
          "推荐",
          "高蛋白"
        ]
      },
      {
        "name": "鲜虾牛油果沙拉",
        "kcal_range": "250-310",
        "protein_g": 22,
        "price_yuan": 32,
        "warnings": [],
        "tags": [
          "推荐",
          "低卡",
          "高蛋白"
        ]
      }
    ]
  }
]
